language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: XpGwSE29bMq8903konR4agZgq0IUxua083gzQF01ourb5QF7Yw+w8qzfm1MAVcsw/URedZEjMTqlA0y1EjtXl/EwmF09EcCetCyYx2VnbUFCt0tQHQyR7Fga7bOAkC3QHntV6bLZn8iJ/6Hia1ZotvcGu6DHZJQZBlWXB7qheltBp/f12+nbu9oEUEIJnzv7p3kCfQXWT/kBIiGoBejIQ60qwW0tRVDoIHY3Pdj614ecKFxRnUltUpnCGukDrCSiqM4hfzqPyVHxM5OgpvE0ewilbxdksUw6EhYhLnxgUZrCYRxbrQhAYkV1SpvyG0znA9i9O6K422fuY1AhZ/yOXSR7v5iAn4rVQWWVcYExOIjZyDn4j4oQUZSsnVA1QexLyXZRGcRYvUtTFAUVGFmCP/HqY36svFbLaVYkkERL/7L3Y0niyz7rOe0Lr6wSth5MzrLARsfKHRVIAXmJP2OtsR7nDI0q/lWvWZJXbw/A4z20Rkt5Qx0nl53gz58X24EH8/e5g1wB3yc0tWQhq/N0pLmUIbakhxQg2nt1uSVmCYlPlEfgTMk3ZDbCcyTOLNdQhnzAzF6XrKs8ZIg+krp91TUSFEIq/DrPfAnho80rzpU32Ew6qEIyC17WGzz/x3Inys2fhhtWquwNv0s4dqXD5A9yRFDLmanJN0TCknKA9F4=
  file:
    - 'character-entities-legacy.js'
    - 'character-entities-legacy.min.js'
  on:
    tags: true
