language: node_js
node_js:
- '4.0'
- '8.0'
deploy:
  provider: releases
  api_key:
    secure: MeOE27RPh4hG1qfAH0Csdrk241E33b5D69DcrpF5wcJNsK3OCxXKR1Yf/yPhuhbjkwms0K1yVmzM5y9UwIuPm/1BzmsoM/Y26oNJQ9i+j3VmWp00qr0BaEhUtnzBL/Cqso8ca//FiG3a7TNkmZ56h6gfFBMmvQYJ6D3tknEejFJECZl1eLZwvPgHiT+ku6HXDJxpGWK8QJXmdR3qfhar7tl67rRvu33fdGVJ+qnjkffxEnCbW5wUnCWRpwupeamJykS/ZAV8c4SqAvSB7P8JckQImUWvqdkWjHbeq1fgjMr4x70iY2gsb+ltX3i8DEWag8eWZLr60uyriRebsa4bZ2IGIZSqQyTLE7t3oLh/ebpyIRlzauGz4ZTi7ovdkCGO4Ui4ZOvtyioFx+qMbB5hIm0Xbw5FsPY9geGKkCZ8w6yVRg07fMNIESNbbcrga6vKHn71wZ4vH75ydq7pBtCLYEjNfZO1S97amqzpF6vs+Ve9ikNWEeQuBJDsqYzXIsbIRfCdbiTPcTnh9qDa7g+VKrnTbju1EiOeEvE0MG/F9yBU6CE952LBI3EcAK7Z/U1bit5YgIMbb1KVyFyX5Z6nJrWqDQGsJ6/C9BpcFvUFBlm/ZBmuueEBuxTj9cNG8+ORDCevQDcROfvZh98WtSGmD+gXmBt2AqA5CPe2AgYJa4M=
  file:
    - "character-entities-legacy.js"
    - "character-entities-legacy.min.js"
  on:
    tags: true
    node: '8.0'
